languageCode = "en-us"
title = "complex play lab"
uglyurls = true
canonifyurls = true
theme = "cplburn"
builddrafts = true
baseurl = "/"
#"http://cpl-uw.github.io/"
googleAnalytics = "UA-29814504-2"
paginate = 10

[params]
subtitle = "uw–madison"

[author]
name = "complex play lab"

[permalinks]
# Optional. Change the permalink format for the 'post' content type.
# The format shown here is the same one Jekyll/Octopress uses by default.
post = "/blog/:year/:month/:day/:title/"

[taxonomies]
# Optional. Use if you want tags and lists.
category = "categories"

[[menu.main]]
name = "home"
weight = -110
identifier = "home"
url = "/"

[[menu.main]]
name = "papers"
weight = -110
identifier = "paper"
url = "/paper/"

[[menu.main]]
name = "posts"
weight = -110
identifier = "post"
url = "/post/"

[[menu.main]]
name = "person"
weight = -110
identifier = "person"
url = "/person/"
